grafana:
  enabled: true
  service:
    type: ClusterIP

prometheus:
  enabled: true
  service:
    type: ClusterIP

alertmanager:
  enabled: true
  service:
    type: ClusterIP

nodeExporter:
  enabled: false