apiVersion: v1
kind: Service

metadata:
  name: python-sample
  namespace: default

spec:
  type: ClusterIP

  selector:
    app: python-sample

  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP