apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default

  sources:

    # Official Prometheus Community Helm chart
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 91.8.2

      helm:
        releaseName: kube-prometheus-stack

        valueFiles:
          - $values/apps/monitoring/values.yaml

    # Our Git repository containing the values file
    - repoURL: https://github.com/sanjayramagiri99/ECR-Fargate-Demo.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true